name: 'CI: Frontend'

on:
    push:
        branches: [main]
        paths:
          - 'src/HelloBlazor.Client/**'

    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  PROJECT_PATH: 'src/HelloBlazor.Client'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  CONFIGURATION: 'Release'
  PACKAGE_NAME: 'blazorapp'

jobs:
  build-and-publish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    env:
        CSPROJ_PATH: "$PROJECT_PATH/HelloBlazor.Client.csproj"
        TOML_PATH: "$PROJECT_PATH/netlify.toml"

    steps:

    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: 'Setup .NET Core'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: 'Restore Packages'
      run: dotnet restore ${{ env.CSPROJ_PATH }}

    - name: 'Build'
      run: dotnet build ${{ env.CSPROJ_PATH }} --no-restore --configuration ${{ env.CONFIGURATION }}

    - name: 'Publish'
      run: dotnet publish ${{ env.CSPROJ_PATH }} --configuration ${{ env.CONFIGURATION }} --no-build --no-restore --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} --nologo 

    - name: 'Copy Netlify toml File' 
      run: |
        cp ${{ env.TOML_PATH }} "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/netlify.toml"

    - name: "Upload Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}