name: 'CD: Frontend'

on:
  workflow_run:
    workflows: ["CI WebApp 452"]
    types: [completed]

   workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  PACKAGE_NAME: 'blazorapp'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:

    - name: 'Download Artifact'
      uses: dawidd6/action-download-artifact@v2
      with:
       workflow: ${{ github.event.workflow_run.workflow_id }}
       workflow_conclusion: success
       name: ${{ env.PACKAGE_NAME }}
    
    - name: 'Deploy to Netlify'
      id: deploy
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: ./wwwroot
        netlify-config-path: ./netlify.toml
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: ${{ github.event.pull_request.title }}
        alias: ${{ github.head_ref }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1